### ISSUE TITLE
how do you identify a trope the first time it is used? is there an ur-trope?

### ISSUE THREAD

**Issue by jwzimmer** [jwzimmer/tv-tropening#1]
part of the definition of trope is that it occurs in many works. it's a class that is instantiated lots of times. but for every trope we can identify now, there must* be a first time it was used. If you saw that trope at that time, is there any way of telling that it is a new trope? Is that deterministic? or is that only something that happens "once the ball is rolling" and the trope is being used in multiple works?

*maybe. Or maybe all tropes spawn from previous tropes such that there is no solid delineation between them, merely gradual mutations that turn into their own tropes. But then is there an ur-trope, identifiable via reconstruction like e.g. proto-indo-european words via changes across subsequent languages?

**Comment by JJ** [comment]
There's, curiously enough, a [trope codifier](https://tvtropes.org/pmwiki/pmwiki.php/Main/TropeCodifier) trope. Very few movies list that trope, and there's not a movie listed for every trope. But it shouldn't be too difficult to find the first movie that got that trope attached... first approximation, if the movie lists its date, second approximation by checking page history and comparing dates.

**Comment by jwzimmer** [comment]
> There's, curiously enough, a [trope codifier](https://tvtropes.org/pmwiki/pmwiki.php/Main/TropeCodifier) trope. Very few movies list that trope, and there's not a movie listed for every trope. But it shouldn't be too difficult to find the first movie that got that trope attached... first approximation, if the movie lists its date, second approximation by checking page history and comparing dates.

Wonderful idea, thank you for the suggestion!

**Comment by jwzimmer** [comment]
I want to come back to this later! We could make a really cool graphic showing a timeline for the tropes per JJ's suggestion above. But for now since we are proximally focusing on the character space project, I will close this issue. : (
